In [1]:
import gym
from model import Actor, Critic
from matplotlib import pyplot as plt
%matplotlib inline

env = gym.make("CarRacing-v1")

2022-07-16 21:16:54.758168: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-07-16 21:16:54.758212: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
/home/mortimer/.local/lib/python3.10/site-packages/flatbuffers/compat.py:19: DeprecationWarning: the imp module is deprecated in favour of importlib and slated for removal in Python 3.12; see the module's documentation for alternative uses
  import imp
/home/mortimer/.local/lib/python3.10/site-packages/keras/utils/image_utils.py:36: DeprecationWarning: NEAREST is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.NEAREST or Dither.NONE instead.
  'nearest': pil_image.NEAREST,
/home/mortimer/.local/lib/python3.10/site-packages/keras/utils/image_utils.py:37: DeprecationWarning: BILINEA

In [2]:
agent = Vanilla(env_name="CarRacing-v1", n_proc=16, actor=Actor)
history = agent(1024)
plt.plot(range(len(history)), history)
plt.title('Scores over Episode')
plt.xlabel('Episode')
plt.ylabel('Score')
plt.show()

In [3]:
agent = PPO(env_name="CarRacing-v1", n_proc=16, actor=Actor, critic=Critic)
history = agent(1024)
plt.plot(range(len(history)), history)
plt.title('Scores over Episode')
plt.xlabel('Episode')
plt.ylabel('Score')
plt.show()

Track generation: 1021..1280 -> 259-tiles trackTrack generation: 1194..1497 -> 303-tiles trackTrack generation: 1100..1379 -> 279-tiles track
Track generation: 1187..1488 -> 301-tiles track




2022-07-07 12:49:57.505158: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2022-07-07 12:49:57.505185: W tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303)
2022-07-07 12:49:57.505210: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (typewriter): /proc/driver/nvidia/version does not exist
2022-07-07 12:49:57.505852: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


[[ 1.8845575e-02  3.1330380e-06 -1.2164510e-02]
 [ 1.9942464e-02  5.7394869e-27 -1.2082870e-02]
 [ 2.4815300e-02  1.1534585e-02 -1.3269917e-02]
 [ 2.6880495e-02  0.0000000e+00 -1.2127635e-02]]


<tf.Tensor: shape=(), dtype=float32, numpy=nan>

Mu [[ -7.856493   13.435374  -19.321125 ]
 [ -6.5288243  12.018929  -16.405369 ]
 [ -6.739167   10.344818  -17.442099 ]
 [ -5.450582    9.990609  -14.773234 ]]
Sigma [[ 19.416162    2.7355857 -20.401037 ]
 [ 18.745064    1.0955305 -27.681297 ]
 [ 14.865444    4.803723  -19.955502 ]
 [ 13.8821335   0.3600061 -28.469128 ]]
As [[ 0.2161851   0.75203454  0.5572391 ]
 [ 0.23162045  0.07691733  0.03047397]
 [-0.8558698   0.7998415   0.6242406 ]
 [-0.37597877  0.85295844  0.5319229 ]]
tf.Tensor(
[[1.7286552e-01 2.1496447e+01 9.4941652e-01]
 [1.3006987e-01 1.1882450e+02 3.5254216e-01]
 [1.5663393e-01 3.9481514e+00 8.1962466e-01]
 [1.3362622e-01 6.4424255e+02 2.8901958e-01]], shape=(4, 3), dtype=float32)
[[-2.967847   -1.9252627  -3.3124578 ]
 [-2.9128342  -1.0101773  -3.4013047 ]
 [-2.6933064  -2.34944    -3.2486687 ]
 [-2.6141713   0.10269584 -3.4023123 ]]


<tf.Tensor: shape=(), dtype=float32, numpy=-29.735088>